settings:
  username: "javierdebug" 
  commit_msg: "⚡ Update README with the recent activity"
  max_lines: 15
  readme_file: "./README.md"
  disabled_events:
    - "comments"
    - "star"
    - "create_repo"
  #url_text: "{REPO}{ID}"
  date:
    timezone: "GMT-5:00"
    text: "Last Updated: {DATE}"
    #format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  ignored_repos:
    - javierdebug/javierdebug
messages:
  comments: "![comment] Commented on {ID} in {REPO}"
  issue_opened: "![issueOpened] Opened issue {ID} in {REPO}"
  issue_closed: "![issueClosed] Closed issue {ID} in {REPO}"
  pr_opened: "![prOpened] Opened PR {ID} in {REPO}"
  pr_closed: "![prClosed] Closed PR {ID} in {REPO}"
  pr_merged: "![prMerged] Merged PR {ID} in {REPO}"
  create_repo: "![repoCreated] Created new repository {REPO}"
  fork_repo: "![fork] Forked {FORK} from {REPO}"
  wiki_create: "![wiki] Created new wiki page {WIKI} in {REPO}"
  added_member: "![people] Became collaborator on {REPO}"
  changes_approved: "![approved] Approved {ID} in {REPO}"
  changes_requested: "![changesRequested] Requested changes in {ID} in {REPO}"
  new_release: "![release] Released {ID} in {REPO}"
  new_star: "![star] Starred {REPO}"
  push: "⬆️ Pushed {AMOUNT} commit(s) to {REPO}"
